import { z } from 'zod';

const output = z.enum(['original', 'jpeg', 'png', 'webp', 'avif']);
const quality = z.number().int().min(1).max(100).optional();

export const operationSchema = z.discriminatedUnion('kind', [
  z.object({
    kind: z.literal('compress'),
    mode: z.enum(['smart', 'exact', 'quality', 'lossless']),
    format: output.default('original'),
    quality,
    targetBytes: z.number().int().min(1024).max(104_857_600).optional(),
    minQuality: z.number().int().min(1).max(95).optional(),
    preserveMetadata: z.boolean().optional(),
    aggressive: z.boolean().optional(),
    maxWidth: z.number().int().min(1).max(50_000).optional(),
    maxHeight: z.number().int().min(1).max(50_000).optional(),
  }),
  z.object({
    kind: z.literal('resize'),
    width: z.number().int().min(1).max(50_000).optional(),
    height: z.number().int().min(1).max(50_000).optional(),
    percentage: z.number().min(1).max(500).optional(),
    fit: z.enum(['cover', 'contain', 'fill', 'inside', 'outside']).optional(),
    background: z.string().max(32).optional(),
    format: output.default('original'),
    quality,
    preserveMetadata: z.boolean().optional(),
  }),
  z.object({
    kind: z.literal('crop'),
    left: z.number().int().min(0),
    top: z.number().int().min(0),
    width: z.number().int().min(1),
    height: z.number().int().min(1),
    format: output.default('original'),
    quality,
  }),
  z.object({
    kind: z.literal('rotate'),
    degrees: z.union([z.literal(90), z.literal(180), z.literal(270)]),
    format: output.default('original'),
    quality,
  }),
  z.object({
    kind: z.literal('convert'),
    format: z.enum(['jpeg', 'png', 'webp', 'avif']),
    quality,
    background: z.string().max(32).optional(),
  }),
  z.object({
    kind: z.literal('metadata'),
    action: z.enum(['inspect', 'remove']),
    format: output.optional(),
  }),
  z.object({
    kind: z.literal('prepare'),
    width: z.number().int().min(16).max(10_000),
    height: z.number().int().min(16).max(10_000),
    targetBytes: z.number().int().min(1024).max(50_000_000).optional(),
    minBytes: z.number().int().min(0).max(50_000_000).optional(),
    format: z.enum(['jpeg', 'png']),
    quality,
    background: z.string().max(32).default('#ffffff'),
    density: z.number().int().min(36).max(1200).optional(),
    trim: z.boolean().optional(),
    fit: z.enum(['cover', 'contain']).default('cover'),
    position: z.enum(['centre', 'north', 'south', 'east', 'west']).optional(),
  }),
  z.object({
    kind: z.literal('watermark'),
    text: z.string().min(1).max(160),
    position: z.enum([
      'northwest',
      'north',
      'northeast',
      'west',
      'center',
      'east',
      'southwest',
      'south',
      'southeast',
    ]),
    opacity: z.number().min(0.05).max(1),
    scale: z.number().min(0.03).max(0.5),
    padding: z.number().int().min(0).max(500),
    format: output.default('original'),
  }),
  z.object({
    kind: z.literal('favicon'),
    fit: z.enum(['contain', 'cover']).optional(),
    background: z.string().max(32).optional(),
  }),
]);
